;;; pichat-test-sessions-source-navigation.el --- Source navigation tests -*- lexical-binding: t; -*-

;;; Commentary:

;; Focused Phase 9 tests for persisted fork/clone source navigation.

;;; Code:

(require 'pichat-test-sessions-clone)

(ert-deftest pichat-sessions-rebind-transactions-commit-persisted-origins ()
  (pichat-test-sessions-fork--with-origin
    (let (fork-success fork-state clone-success clone-state)
      (setf (pichat-session-session-file-forward-stack session) '("/old-future"))
      (pichat-sessions--goto-id "alternate-user")
      (cl-letf (((symbol-function 'pichat-rpc-fork)
                 (lambda (_session _id success _failure)
                   (setq fork-success success)))
                ((symbol-function 'pichat-rpc-clone)
                 (lambda (_session success &optional _failure)
                   (setq clone-success success)))
                ((symbol-function 'pichat-rpc-get-state)
                 (lambda (_session success _failure)
                   (if fork-success
                       (prog1 (setq fork-state success) (setq fork-success nil))
                     (setq clone-state success))))
                ((symbol-function 'pichat-sessions--finish-fork) #'ignore)
                ((symbol-function 'pichat-sessions--finish-clone) #'ignore)
                ((symbol-function 'yes-or-no-p) (lambda (&rest _args) t)))
        (pichat-sessions-fork-at-point)
        (funcall fork-success '(:success t :data (:text "prompt")) session)
        (should-not (pichat-session-session-file-back-stack session))
        (setf (pichat-session-session-file session) "/forked")
        (funcall fork-state '(:success t :data (:sessionFile "/forked")) session)
        (should (equal '("/source")
                       (pichat-session-session-file-back-stack session)))
        (should-not (pichat-session-session-file-forward-stack session))
        (pichat-sessions-clone-current)
        (funcall clone-success '(:success t :data nil) session)
        (setf (pichat-session-session-file session) "/cloned")
        (funcall clone-state '(:success t :data (:sessionFile "/cloned")) session)
        (should (equal '("/forked" "/source")
                       (pichat-session-session-file-back-stack session)))
        (should-not (pichat-session-session-file-forward-stack session))))))

(ert-deftest pichat-sessions-rebind-cancel-failure-and-unsynced-target-keep-stacks ()
  (dolist (kind '(fork clone))
    (let ((session (pichat-session-make
                    :session-file "/source"
                    :session-file-back-stack '("/older")
                    :session-file-forward-stack '("/future")))
          command-success command-failure state-failure)
      (cl-letf (((symbol-function 'pichat-rpc-fork)
                 (lambda (_session _id success failure)
                   (setq command-success success command-failure failure)))
                ((symbol-function 'pichat-rpc-clone)
                 (lambda (_session success &optional failure)
                   (setq command-success success command-failure failure)))
                ((symbol-function 'pichat-rpc-get-state)
                 (lambda (_session _success failure) (setq state-failure failure)))
                ((symbol-function 'message) #'ignore))
        (dotimes (attempt 3)
          (let ((context (list :session session :source-file "/source"
                               :entry-id "user")))
            (if (eq kind 'fork)
                (pichat-sessions--request-fork context)
              (pichat-sessions--request-clone context)))
          (pcase attempt
            (0 (funcall command-success
                        '(:success t :data (:cancelled t)) session))
            (1 (funcall command-failure
                        '(:success nil :error "denied") session))
            (2 (funcall command-success '(:success t :data nil) session)
               (funcall state-failure
                        '(:success nil :error "state timeout") session)))
          (should (equal '("/older")
                         (pichat-session-session-file-back-stack session)))
          (should (equal '("/future")
                         (pichat-session-session-file-forward-stack session))))))))

(ert-deftest pichat-sessions-rebind-origin-requires-persisted-source-and-target ()
  (let ((session (pichat-session-make :session-file "/target"
                                      :session-file-forward-stack '("/future"))))
    (pichat-sessions--commit-rebind-origin
     (list :session session :source-file nil))
    (should-not (pichat-session-session-file-back-stack session))
    (should-not (pichat-session-session-file-forward-stack session))
    (setf (pichat-session-session-file session) nil
          (pichat-session-session-file-back-stack session) '("/older")
          (pichat-session-session-file-forward-stack session) '("/future"))
    (pichat-sessions--commit-rebind-origin
     (list :session session :source-file "/source"))
    (should-not (pichat-session-session-file-back-stack session))
    (should-not (pichat-session-session-file-forward-stack session))))

(ert-deftest pichat-sessions-source-navigation-peeks-then-commits-symmetrically ()
  (let ((session (pichat-session-make
                  :session-file "/forked"
                  :session-file-back-stack '("/origin")))
        switch-success state-success sent-target focused)
    (cl-letf (((symbol-function 'pichat-rpc-switch-session)
               (lambda (_session target success &optional _failure)
                 (setq sent-target target switch-success success)))
              ((symbol-function 'pichat-rpc-get-state)
               (lambda (_session success _failure) (setq state-success success)))
              ((symbol-function 'pichat-sessions--focus-navigated-session)
               (lambda (_session direction target _source)
                 (setq focused (list direction target)))))
      (with-temp-buffer
        (setq-local pichat-sessions-session session)
        (pichat-sessions-return-to-origin))
      (should (equal "/origin" sent-target))
      (should (equal '("/origin")
                     (pichat-session-session-file-back-stack session)))
      (should-not (pichat-session-session-file-forward-stack session))
      (funcall switch-success '(:success t :data nil) session)
      (should-not (pichat-session-session-file-back-stack session))
      (should (equal '("/forked")
                     (pichat-session-session-file-forward-stack session)))
      (should state-success)
      (setf (pichat-session-session-file session) "/origin")
      (funcall state-success '(:success t :data (:sessionFile "/origin")) session)
      (should (equal '(back "/origin") focused))
      (setq switch-success nil state-success nil focused nil)
      (with-temp-buffer
        (setq-local pichat-sessions-session session)
        (pichat-sessions-forward-to-fork))
      (should (equal "/forked" sent-target))
      (should-not (pichat-session-session-file-back-stack session))
      (should (equal '("/forked")
                     (pichat-session-session-file-forward-stack session)))
      (funcall switch-success '(:success t :data nil) session)
      (should (equal '("/origin")
                     (pichat-session-session-file-back-stack session)))
      (should-not (pichat-session-session-file-forward-stack session))
      (setf (pichat-session-session-file session) "/forked")
      (funcall state-success '(:success t :data (:sessionFile "/forked")) session)
      (should (equal '(forward "/forked") focused)))))

(ert-deftest pichat-sessions-source-navigation-cancel-and-failure-keep-stacks ()
  (dolist (outcome '(cancel failure))
    (let ((session (pichat-session-make
                    :session-file "/forked"
                    :session-file-back-stack '("/origin")
                    :session-file-forward-stack '("/later")))
          switch-success switch-failure state-requested messages)
      (cl-letf (((symbol-function 'pichat-rpc-switch-session)
                 (lambda (_session _target success &optional failure)
                   (setq switch-success success switch-failure failure)))
                ((symbol-function 'pichat-rpc-get-state)
                 (lambda (&rest _args) (setq state-requested t)))
                ((symbol-function 'message)
                 (lambda (&rest args) (push args messages))))
        (with-temp-buffer
          (setq-local pichat-sessions-session session)
          (pichat-sessions-return-to-origin))
        (if (eq outcome 'cancel)
            (funcall switch-success '(:success t :data (:cancelled t)) session)
          (funcall switch-failure '(:success nil :error "switch denied") session)))
      (should (equal '("/origin")
                     (pichat-session-session-file-back-stack session)))
      (should (equal '("/later")
                     (pichat-session-session-file-forward-stack session)))
      (should-not state-requested)
      (should (cl-some
               (lambda (args)
                 (string-match-p (if (eq outcome 'cancel) "cancelled" "switch denied")
                                 (apply #'format args)))
               messages)))))

(ert-deftest pichat-sessions-source-navigation-keeps-commit-on-state-failure ()
  (let ((session (pichat-session-make
                  :session-file "/forked"
                  :session-file-back-stack '("/origin")))
        switch-success state-failure messages)
    (cl-letf (((symbol-function 'pichat-rpc-switch-session)
               (lambda (_session _target success &optional _failure)
                 (setq switch-success success)))
              ((symbol-function 'pichat-rpc-get-state)
               (lambda (_session _success failure) (setq state-failure failure)))
              ((symbol-function 'message)
               (lambda (&rest args) (push args messages))))
      (with-temp-buffer
        (setq-local pichat-sessions-session session)
        (pichat-sessions-return-to-origin))
      (funcall switch-success '(:success t :data nil) session)
      (should-not (pichat-session-session-file-back-stack session))
      (should (equal '("/forked")
                     (pichat-session-session-file-forward-stack session)))
      (funcall state-failure '(:success nil :error "state timeout") session)
      (should-not (pichat-session-session-file-back-stack session))
      (should (equal '("/forked")
                     (pichat-session-session-file-forward-stack session)))
      (should (cl-some
               (lambda (args)
                 (let ((text (apply #'format args)))
                   (and (string-match-p "session changed" text)
                        (string-match-p "state timeout" text))))
               messages)))))

(ert-deftest pichat-sessions-source-navigation-rejects-missing-persisted-paths ()
  (dolist (session (list (pichat-session-make :session-file nil
                                               :session-file-back-stack '("/origin"))
                         (pichat-session-make :session-file "/forked")
                         (pichat-session-make :session-file "/forked"
                                              :session-file-back-stack '(nil))))
    (let (sent)
      (cl-letf (((symbol-function 'pichat-rpc-switch-session)
                 (lambda (&rest _args) (setq sent t))))
        (with-temp-buffer
          (setq-local pichat-sessions-session session)
          (should-error (pichat-sessions-return-to-origin) :type 'user-error)))
      (should-not sent))))

(ert-deftest pichat-sessions-unrelated-navigation-clears-stacks-only-on-success ()
  (let ((session (pichat-session-make
                  :session-file "/current"
                  :session-file-back-stack '("/origin")
                  :session-file-forward-stack '("/fork")))
        new-success switch-success state-success)
    (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _args) t))
              ((symbol-function 'pichat-rpc-new-session)
               (lambda (_session success &optional _parent)
                 (setq new-success success)))
              ((symbol-function 'pichat-rpc-get-state)
               (lambda (_session success &rest _args) (setq state-success success))))
      (with-temp-buffer
        (setq-local pichat-chat-session session)
        (pichat-chat-new-session))
      (funcall new-success '(:success t :data (:cancelled t)) session)
      (should (equal '("/origin")
                     (pichat-session-session-file-back-stack session)))
      (funcall new-success '(:success t :data nil) session)
      (should-not (pichat-session-session-file-back-stack session))
      (should-not (pichat-session-session-file-forward-stack session)))
    (setf (pichat-session-session-file-back-stack session) '("/origin")
          (pichat-session-session-file-forward-stack session) '("/fork"))
    (cl-letf (((symbol-function 'pichat-consult-available-p) (lambda () nil))
              ((symbol-function 'pichat-sessions--root-dir) (lambda () "/saved/"))
              ((symbol-function 'pichat-sessions--files) (lambda () '("/saved/one")))
              ((symbol-function 'pichat-sessions--file-choices)
               (lambda (&rest _args) '(("one" . "/saved/one"))))
              ((symbol-function 'pichat-sessions--file-summary)
               (lambda (&rest _args) nil))
              ((symbol-function 'completing-read) (lambda (&rest _args) "one"))
              ((symbol-function 'pichat-sessions--active-session) (lambda () session))
              ((symbol-function 'pichat-rpc-switch-session)
               (lambda (_session _file success &optional _failure)
                 (setq switch-success success)))
              ((symbol-function 'pichat-rpc-get-state)
               (lambda (_session success &rest _args) (setq state-success success))))
      (pichat-sessions-browse-files)
      (funcall switch-success '(:success t :data (:cancelled t)) session)
      (should (equal '("/origin")
                     (pichat-session-session-file-back-stack session)))
      (funcall switch-success '(:success t :data nil) session)
      (should-not (pichat-session-session-file-back-stack session))
      (should-not (pichat-session-session-file-forward-stack session)))))

(provide 'pichat-test-sessions-source-navigation)
;;; pichat-test-sessions-source-navigation.el ends here
