;;; pichat-test-sessions-clone.el --- Complete clone transaction tests -*- lexical-binding: t; -*-

;;; Commentary:

;; Focused Phase 8 tests for cloning the current active branch.

;;; Code:

(require 'pichat-test-sessions-fork)

(ert-deftest pichat-sessions-clone-targets-current-active-branch-not-row ()
  (pichat-test-sessions-fork--with-origin
    (let (clone-session confirmation selected-row-read)
      (pichat-sessions--goto-id "alternate-user")
      (cl-letf (((symbol-function 'pichat-sessions--entry-id-at-point)
                 (lambda () (setq selected-row-read t) "wrong-row"))
                ((symbol-function 'yes-or-no-p)
                 (lambda (prompt) (setq confirmation prompt) t))
                ((symbol-function 'pichat-rpc-clone)
                 (lambda (rpc-session _success &optional _error)
                   (setq clone-session rpc-session)
                   "clone-request")))
        (pichat-sessions-clone-current))
      (should (eq session clone-session))
      (should-not selected-row-read)
      (should (string-match-p "current active branch" confirmation)))))

(ert-deftest pichat-sessions-clone-declined-cancelled-and-failed-preserve-origin ()
  (pichat-test-sessions-fork--with-origin
    (let (clone-success clone-failure state-success state-failure focused messages
          (clone-calls 0))
      (pichat-sessions--goto-id "alternate-user")
      (let ((before (buffer-string))
            (position (point)))
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (_prompt) nil))
                  ((symbol-function 'pichat-rpc-clone)
                   (lambda (&rest _args) (cl-incf clone-calls))))
          (pichat-sessions-clone-current))
        (should (= 0 clone-calls))
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (_prompt) t))
                  ((symbol-function 'pichat-rpc-clone)
                   (lambda (_session success &optional failure)
                     (cl-incf clone-calls)
                     (setq clone-success success clone-failure failure)
                     "clone-request"))
                  ((symbol-function 'pichat-rpc-get-state)
                   (lambda (_session success failure)
                     (setq state-success success state-failure failure)))
                  ((symbol-function 'pop-to-buffer)
                   (lambda (&rest _args) (setq focused t)))
                  ((symbol-function 'message)
                   (lambda (&rest args) (push args messages))))
          (pichat-sessions-clone-current)
          (funcall clone-success '(:success t :data (:cancelled t)) session)
          (should-not state-success)
          (should-not focused)
          (should (equal before (buffer-string)))
          (should (= position (point)))
          (pichat-sessions-clone-current)
          (funcall clone-failure '(:success nil :error "Cannot clone an empty session")
                   session)
          (should-not state-success)
          (should-not focused)
          (should (equal before (buffer-string)))
          (should (= position (point)))
          (pichat-sessions-clone-current)
          (funcall clone-success '(:success t :data nil) session)
          (should state-failure)
          (funcall state-failure '(:success nil :error "state timeout") session)
          (should-not focused)
          (should (equal before (buffer-string)))
          (should (= position (point)))
          (should (cl-some
                   (lambda (args)
                     (string-match-p "cancelled" (apply #'format args)))
                   messages))
          (should (cl-some
                   (lambda (args)
                     (string-match-p "Cannot clone an empty session"
                                     (apply #'format args)))
                   messages))
          (should (cl-some
                   (lambda (args)
                     (let ((text (apply #'format args)))
                       (and (string-match-p "session changed" text)
                            (string-match-p "state timeout" text))))
                   messages)))))))

(ert-deftest pichat-sessions-clone-success-refreshes-identity-and-focuses-preserved-chat ()
  (pichat-test-sessions-fork--with-origin
    (let ((chat (generate-new-buffer " *pichat-clone-chat*"))
          clone-success state-success state-failure focused messages
          repaint-called open-called)
      (unwind-protect
          (progn
            (with-current-buffer chat
              (pichat-chat-mode)
              (pichat-chat--insert-header session)
              (pichat-chat--insert-prompt)
              (setq-local pichat-chat-session session)
              (pichat-chat--set-input-text "keep this draft")
              (setq-local pichat-chat--pending-attachments '(pending-image)
                          pichat-chat--recoverable-submissions '(recoverable-image))
              (puthash "request" '(in-flight-image)
                       pichat-chat--in-flight-attachments))
            (setf (pichat-session-buffer session) chat)
            (cl-letf (((symbol-function 'yes-or-no-p) (lambda (_prompt) t))
                      ((symbol-function 'pichat-rpc-clone)
                       (lambda (_session success &optional _failure)
                         (setq clone-success success)
                         "clone-request"))
                      ((symbol-function 'pichat-rpc-get-state)
                       (lambda (_session success failure)
                         (setq state-success success state-failure failure)
                         "state-request"))
                      ((symbol-function 'pichat-chat-open)
                       (lambda (&rest _args) (setq open-called t)))
                      ((symbol-function 'pichat-chat-repaint)
                       (lambda () (setq repaint-called t)))
                      ((symbol-function 'pop-to-buffer)
                       (lambda (buffer &rest _args) (setq focused buffer)))
                      ((symbol-function 'message)
                       (lambda (&rest args) (push args messages))))
              (pichat-sessions-clone-current)
              (funcall clone-success '(:success t :data nil) session)
              (should state-success)
              (should-not focused)
              (should-not messages)
              (setf (pichat-session-id session) "cloned-session"
                    (pichat-session-session-file session) "/sessions/cloned.jsonl")
              (funcall state-success '(:success t :data (:sessionId "cloned-session"))
                       session)
              (should (eq chat focused))
              (should-not open-called)
              (should-not repaint-called)
              (with-current-buffer chat
                (should (equal "keep this draft" (pichat-chat--input-text)))
                (should (equal '(pending-image)
                               pichat-chat--pending-attachments))
                (should (equal '(recoverable-image)
                               pichat-chat--recoverable-submissions))
                (should (equal '(in-flight-image)
                               (gethash "request"
                                        pichat-chat--in-flight-attachments))))
              (should (cl-some
                       (lambda (args)
                         (let ((text (apply #'format args)))
                           (and (string-match-p "cloned-session" text)
                                (string-match-p "/sessions/cloned.jsonl" text))))
                       messages))))
        (kill-buffer chat)))))

(ert-deftest pichat-sessions-clone-opens-after-state-with-authoritative-sync ()
  (pichat-test-sessions-fork--with-origin
    (let (clone-success state-success opened-session synchronize focused)
      (cl-letf (((symbol-function 'yes-or-no-p) (lambda (_prompt) t))
                ((symbol-function 'pichat-rpc-clone)
                 (lambda (_session success &optional _failure)
                   (setq clone-success success)))
                ((symbol-function 'pichat-rpc-get-state)
                 (lambda (_session success _failure) (setq state-success success)))
                ((symbol-function 'pichat-chat-open)
                 (lambda (rpc-session &optional sync)
                   (setq opened-session rpc-session synchronize sync)
                   (get-buffer-create " *pichat-new-clone-chat*")))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buffer &rest _args) (setq focused buffer))))
        (unwind-protect
            (progn
              (setf (pichat-session-buffer session) nil)
              (pichat-sessions-clone-current)
              (funcall clone-success '(:success t :data nil) session)
              (setf (pichat-session-id session) "new-clone")
              (funcall state-success '(:success t :data (:sessionId "new-clone"))
                       session)
              (should (eq session opened-session))
              (should synchronize)
              (should (eq focused (get-buffer " *pichat-new-clone-chat*"))))
          (when-let ((buffer (get-buffer " *pichat-new-clone-chat*")))
            (kill-buffer buffer)))))))

(provide 'pichat-test-sessions-clone)
;;; pichat-test-sessions-clone.el ends here
